spring:
  application:
    name: bushub-core

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/bushub_core
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhc-pool

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: false
    mixed: true
    out-of-order: true
    table: schema_version

#------------------------------------
# Server settings
#------------------------------------

server:
  port: 6003
  servlet:
    context-path: /api
